#mrna
rna_codon_table = {
    'F': 2, 'L': 6, 'I': 3, 'M': 1,
    'V': 4, 'S': 6, 'P': 4, 'T': 4,
    'A': 4, 'Y': 2, 'H': 2, 'Q': 2,
    'N': 2, 'K': 2, 'D': 2, 'E': 2,
    'C': 2, 'W': 1, 'R': 6, 'G': 4,
    'STOP': 3
}

def calculate_rna_possibilities(protein_sequence, codon_table):
    possibilities = 1
    for symbol in protein_sequence:
        if symbol not in codon_table:
            raise ValueError(f"Unknown amino acid symbol: {symbol}")
        possibilities = (possibilities * codon_table[symbol]) % 1000000
    #recognition of the stop codon for the translation
    possibilities = (possibilities * codon_table['STOP']) % 1000000
    return possibilities

protein_sequence = 'MSHASCHHNFLNGKVWCCFEKDPNYNYRKKCNLRTCGSNEILNDTLWRIHSVFMEAVTKHTIFIYGCHQGYPAGVMDWELPQASSDWLSFQEPMGRNVISVMDVQRFANDKQSYKWRCQEFTFLLEQRVYPVSTRWQRYQTTMFTMAEGTYLVAVPNFCSWAKTDDYGTGCNKWNVMEMCSFYEKECTRLRTPKKNHKQRWCYDRIIMLNLCYIYRVSQVFHWGYGCWIILCNQMICYNLQWKQFNLKDHGENTPHYKSFWNNYMILQDWNRFEYILMYCMFGCSDWPALDRECMKLANYWVNVTMWRTDCLGRPHGRLQWPSQFSCFVEANKDRPKNYEAHVGRTFSVTKDRWNIEATRLRIQSMQLDHERWRHLNMAMPYTSGIDTSPRTSTQIDMAPQFLQETKYNCWDGDDDQYFGFQGRPWPNQVPTLAWVQSRCDEDVGKPSQDSPYMNCEAKPPHRDFGKDVFELSQTLFREGNKSFICIEHHNLSQVQYQKRHNQIFCEAMIFYIMCYMDYSYRIGLECHWCGFGVWQWPRKNPKSMWWWTQKWCYQFTFYEWVCMVIVLIQTFTWIYMKYWKTWRCLSFWQEPHVMRMHAWRRMCLFGQYKAERLFWEHGWLHNGDPNGNPKRQLWLWCLHTIKHPVPFNIFSIPFKWYENGYFWRLPKSRMRMASVFAGMNQVDNIFHFVRNVGQIYTVQLWARRVHLHNRANSWAFYRRRIHFHTKMDCNEACQCCDRGFSPWYHHLYMYCHCLDKEVWCVWTQEFDAIAMDVFCMCTLSTNPCKSNTEASHNTWKMQRDGEFIKAYQIYLSHNHAWSPQVKPCLNEFDLEGTRELVQFFPWNQRMKYMHDTQIESVIISLEYTCFSNMEGGEFTSKVRTQAPYMHDAWMMHFIMKKKHDPTMRSAARSHMEEIHQGKAWFNWFYWNNMCMIWTSKNAEHVDVYYIHSASPMCERPQTIHHEVAVAYPKRSPMEKKGRCPHTNTNEQNGIWFIYVVRF'
rna_possibilities = calculate_rna_possibilities(protein_sequence, rna_codon_table)
print(rna_possibilities)

